import SpinGlass.Replicas
import SpinGlass.GuerraBound
import SpinGlass.KS_inequality
import IndependentEndpoint
import Mathlib.Analysis.SpecialFunctions.Artanh
import Mathlib.Analysis.Convex.SpecificFunctions.Basic
import Mathlib.Analysis.Convex.Jensen
import Mathlib.Analysis.Convex.Integral
import Mathlib.MeasureTheory.Integral.Prod

#check HasDerivAt.comp
#check HasDerivAt.scomp
#check HasFDerivAt.comp
#check HasFDerivAt.prod
#check HasFDerivAt.prodMk
#check HasFDerivAt.clm_apply
#check HasFDerivAt.apply
#check HasDerivAt.fun_add
#check HasDerivAt.add
#check HasDerivAt.comp_of_eq
#check DifferentiableAt.prod
#check DifferentiableAt.clm_apply
#check HasFDerivAt.comp₂
#check HasDerivAt.comp₂
#check fderiv_prod
#check fderiv_comp
#check fderiv_clm_apply
#check HasFDerivAt.hasDerivAt
#check HasDerivAt.hasFDerivAt
#check ContinuousLinearMap.map_add
#check ContinuousLinearMap.prod_apply
#check ContinuousLinearMap.inl_apply
#check ContinuousLinearMap.inr_apply
