import SYK.super_concentration.super_conc
import Mathlib.Analysis.Matrix.Order
import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.ExpLog.Basic
open scoped MatrixOrder
#check CFC.exp_eq_normedSpace_exp
#check CFC.real_exp_eq_normedSpace_exp
#check CFC.isStrictlyPositive_exp
#check cfc_isStrictlyPositive_iff
#check Matrix.isStrictlyPositive_iff_posDef
#check Matrix.PosDef.trace_pos
#check Matrix.PosDef.trace_nonneg
#check Matrix.PosSemidef.trace_nonneg
#check Matrix.PosDef.smul
#check Matrix.PosSemidef.smul
#check Matrix.PosSemidef.smul_nonneg
#check HasDerivAt.clog
#check HasDerivAt.log
#check Complex.hasDerivAt_log
#check Real.hasDerivAt_log
#check Matrix.traceLinearMap
#check LinearMap.toContinuousLinearMap
#check LinearMap.continuous_of_finiteDimensional
#check HasFDerivAt.clm_apply
#check HasDerivAt.clm_apply
#check HasFDerivAt.continuousLinearMap_apply
#check HasDerivAt.const_mul
#check HasDerivAt.mul
#check HasDerivAt.smul_const
#check HasDerivAt.const_smul
#check HasDerivAt.clm_apply
#check HasDerivAt.const_clm_apply
#check HasFDerivAt.const_clm_apply
#check HasDerivAt.fun_pow'
#check NormedSpace.exp_eq_tsum_div
#check NormedSpace.exp_eq_tsum
#check NormedSpace.exp_eq_tsum_rat
#check NormedSpace.expSeries_apply_eq
#check Summable.clm_apply
#check Summable.map
#check Summable.comp_injective
#check Summable.mul_left
#check ContinuousLinearMap.map_tsum
#check Summable.sum_add_tsum_nat_add
#check Summable.tsum_mul_left
#check HasSum.mul_left
#check HasDerivAt.re
#check HasDerivAt.ofReal_comp
#check HasDerivAt.log
#check Convex.norm_sub_le
#check convex_univ
#check Convex.isPreconnected
#check exists_ratio_hasDerivAt_eq_slope
#check exists_eq_slope
#check norm_sub_le_of_deriv_le
#check Nat.choose_le_pow_div
#check abs_real_inner_le_norm
#check real_inner_self_eq_norm_sq
#check EuclideanSpace.norm_sq_eq
#check PiLp.norm_sq_eq
#check expSeries_apply_eq
#check exp_eq_tsum_div
