import SpinGlass.Replicas
import Mathlib.Probability.Distributions.Gaussian.HasGaussianLaw.Independence
#check ContinuousLinearMap.lsmul
#check ContinuousLinearMap.smulRight
#check ContinuousLinearMap.id
#check ProbabilityTheory.HasLaw.mk
#check ProbabilityTheory.HasGaussianLaw.map_fun
#check ProbabilityTheory.iIndepFun.hasGaussianLaw_fun_sum
#check ContinuousLinearMap.apply
#check ProbabilityTheory.iIndepFun_pi
#check MeasureTheory.measurePreserving_eval
#check ProbabilityTheory.HasLaw.hasGaussianLaw
#check ProbabilityTheory.IsGaussian.ext
#check ProbabilityTheory.covarianceBilin_apply
#check ContinuousLinearMap.proj
#check ContinuousLinearMap.pi
#check PiLp.continuousLinearEquiv
#check ProbabilityTheory.iIndepFun.indepFun
#check ProbabilityTheory.iIndepFun.indepFun_finset
#check ProbabilityTheory.integral_id_gaussianReal
#check ProbabilityTheory.integral_sq_gaussianReal_centered
#check MeasureTheory.integral_map
#check MeasureTheory.Integrable.comp_quasiMeasurePreserving
#check ProbabilityTheory.IndepFun.integral_mul_eq_mul_integral
#check MeasureTheory.Integrable.of_norm
#check MeasureTheory.eval_integral_piLp
#check MeasureTheory.Integrable.comp_measurePreserving
#check MeasureTheory.MeasurePreserving.integrable_comp_emb
#check MeasureTheory.integral_finset_sum
#check MeasureTheory.Integrable.sum
#check Equiv.curry
#check Equiv.piCongrLeft
#check Fintype.prod_sum
