name = "RequestProject"
defaultTargets = ["disjoint", "cases"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "disjoint"
globs = ["disjoint"]

[[lean_lib]]
name = "cases"
globs = ["cases"]
